### ISSUE TITLE
MMIO will work for DMA - Cheating possible!!

### ISSUE THREAD

**Issue by nonlaminar** [Engr315/Popcount_Autograder#9]
Currently, it is possible for the students to rename their `user_mmio.c` file to `user_dma.c`, and submit it to the DMA auto grader (P6) and pass the correctness tests.

This has a few solutions, none of them too challenging, but requiring a little work on someones part. 

1. Obviously it is possible for the TA's to check this, but it would be good if this could be detected by the autograder. 

Because the DMA lab utilizes the mmio operations, it is not possible to seperate the two in the emulated system, and thus, it cannot be patched at this level. 

2. It would be possible to add some detection in the qemu dma module to detect when the DMA registers are active, but this could lead to unforeseen issues with the operation of the dma, and be difficult to access in userspace.

3. A better solution *may* be a parsing check of the `user_dma.c` check before putting it through the QEMU system, simply matching for the DMA functions and that they are not in commented lines. This would ensure that at the very least the DMA functions are being called somewhere. (perhaps checking the defined DMA registers, and that they appear in reachable code)

@lukefahr, @nicolecathm, @cookce Please be aware of this issue for when the autograder is employed if it has not been patched by then, and please advise on this issue, or if it is a non issue.

Thank you!

**Comment by lukefahr** [comment]
@matteovidali That MMIO works is unavoidable.  The difference is in the runtime.  In real HW, MMIO should run notably slower than DMA.  Is that also the case with QEMU?  Are we checking for runtimes on the AG?

**Comment by nonlaminar** [comment]
@lukefahr Currently, the DMA will run slightly slower than MMIO because it is somewhat of a proxy for the MMIO. It would be possible to make this a little more accurate, and I have a working branch that does the DMA a little more accurately, but it requires some extra setup (setting destination address for dma etc.). 
I could artificially slow down the MMIO operations, but in general they are all just one function call away from the same QEMU memory operations, and thusly there is very little performance difference. 

Currently we are not testing performance, but it would be simple enough with a time statement before running the student binary.

**Comment by lukefahr** [comment]
@matteovidali  I would vote artificially slow down MMIO.  This will match actual physical systems, where there is a ~100 cycle delay caused by the physical transaction to the MMIO.

**Comment by nonlaminar** [comment]
@lukefahr, See linked pullrequest, the [new commit in qemu315](https://github.com/Engr315/qemu315/commit/0da9322a565eea3eaead58c1834851944dcfbebd) - amount of slowdown can be adjusted by manipulating the `MMIO_DELAY` parameter in `popcount.c` and then rebuilding.
